### ISSUE TITLE
Support for multiple InfiniteQueryParams

### ISSUE THREAD

**Issue by fr3fou** [anymaniax/orval#171]
As of now the library only supports a single InfiniteQueryParam - 
![image](https://user-images.githubusercontent.com/1344906/122834711-bfb50a00-d2f7-11eb-8990-a2aa92352688.png)

In some cases endpoints may require 2 (or more) params, meaning one can't use a generated hook, instead they have to fallback to manually calling `useInfiniteQuery` - 
```tsx
useInfiniteQuery(
    "home",
    ({ pageParam }) =>  myPaginatedEndpoint({ foo: pageParam.fooCursor, bar: pageParam.barCursor }),
    {
      getNextPageParam: (lastPage) => ({
        fooCursor: lastPage.fooCursor
        barCursor: lastPage.barCursor,
      }),
    }
  )
```

I propose adding `useInfiniteQueryParams` which is an array, in order to support multiple keys at a time

**Comment by knyzorg** [comment]
The proper fix for this would be to make a the param a function instead of a string, and let it be passed as-is to react-query.

**Comment by createdbymahmood** [comment]
any updates?

**Comment by anymaniax** [comment]
Sorry I cannot check anything before mid September

**Comment by valjusha** [comment]
> Sorry I cannot check anything before mid September

Do you have a result?

**Comment by majkl-zumberi** [comment]
updates on this issue? it would be very nice to handle multiple query params

**Comment by melloware** [comment]
@georgiev-anton is working on this.

**Comment by georgiev-anton** [comment]
yes in this pr #947

**Comment by dawsonbooth** [comment]
We addressed this issue by removing the `useInfiniteQueryParam` global setting, wrapping the generated query hook, and building our own `queryFn` to override the generated one.

Not the cleanest fix, but it works until there's an update made to the settings.

**Comment by pycraft114** [comment]
we need this feature

**Comment by jordan-rigo** [comment]
Do I have to provide "useInfiniteQueryParam"? If I add this this is generate for all my APIs. I dont want that.
Can I not add it to the config, and provide this somehow when trying to use the hook?

**Comment by clementoriol** [comment]
@anymaniax 

This issue should be reopened as it currently still exists. The current way to handle infinite query params with `useInfiniteQueryParam` is not flexible enough for some use cases.


For example, **when using cursor-based pagination**, you can encounter these use-cases : 

### 1/ Multiple params
Your endpoint will usually take a cursor param AND a boolean to know if it need to fetch entries before OR after the cursor.

example : 
```
{ cursor: 10, beforeCursor: true, count: 5 } //  return items [5, 6, 7, 8, 9]
```
```
{ cursor: 10, beforeCursor: false, count: 5 } // return items [11, 12, 13, 14, 15]
```

For these case, we'll need to return 2 params from react-query's `getNextPageParam` and `getPrevPageParam` , and make sure the generated orval hooks passes BOTH the params to the fetch function.
This is currently not possible, as the orval config only supports 1 param.

### 2/ Changing params
Some cursor implementations take inspiration from [relay](https://relay.dev/graphql/connections.htm) and will have different parameters depending on the context.

example : 
```
{ first: 5, before: 10} // return items [5, 6, 7, 8, 9]
```
```
{ first: 5, after: 10 } // return items [11, 12, 13, 14, 15]
```
For these cases, we'll also need to return 2 params from react-query's `getNextPageParam` and `getPrevPageParam`, and those params will change depending if we're fetching the previous or next page.
This is currently not possible, as the orval config only expects a single, hard-coded param.

## Suggested changes
The orval config should be more flexible. IMO, the best way to handle this would be to deprecate the `useInfiniteQueryParam` option and just pass to the query function what is returned from `getNextPageParam` and `getPrevPageParam`

I'll be around if you want to discuss this more

**Comment by melloware** [comment]
@clementoriol can you open a new ticket with your details and possibly provide a PR to fix it?
